VIPER Firmware
MacRover/maxwell pull request #94
Opened 2024-11-20 00:49 UTC by chosterto

2025-01-31 19:40 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +				break;
double break

2025-01-31 19:41 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/can.c
> +      viper_can.id = 0x14;
hardcode to 0x01

2025-01-31 20:24 UTC, chosterto commented on firmware/VIPER/release/Core/Src/can.c
> +    new_message->command_id = (viper_can.RxHeader.ExtId >> CAN_MESSAGE_COMMAND_OFFSET) & (CAN_MESSAGE_COMMAND_MASK);
in addition to `new_message->command_id`, we also want to extract the Card ID from `ExtId` and store it in `new_message->card_id`.

2025-01-31 20:26 UTC, chosterto commented on firmware/VIPER/release/Core/Src/can.c
> +	MX_CAN_Broadcast_Double_Data(&viper_can, state->CARD_0.TEMPERATURE, SEND_CARD_TEMPERATURE, cardx);
You're gonna need some logic here to broadcast data from `CARD_1`, `CARD_2`, and `CARD_3` as well

2025-01-31 20:55 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/can.c
> +              >> 16;
For these four messages, we want the last 8 bits to be FF - so have the offset be CARD_ID_OFFSET instead of DEVICE_ID_OFFSET (which will check if the 11th last to 3rd last pits are 1)

2025-01-31 21:04 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/can.c
> +	MX_CAN_Broadcast_Double_Data(&viper_can, state->CARD_0.OUTPUT_VOLTAGE_B, SEND_CARD_OUTPUT_VOLTAGE_B, cardx);
This should change to whatever cardx ends up being - right now you're only sending card 0 values

2025-01-31 21:04 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +
Need includes for the other drivers once they are merged and instances created

2025-01-31 21:04 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +				break;
double break

2025-01-31 22:11 UTC, chosterto commented on firmware/VIPER/release/Core/Src/can.c
> +    new_message->command_id = (viper_can.RxHeader.ExtId >> CAN_MESSAGE_COMMAND_OFFSET) & (CAN_MESSAGE_COMMAND_MASK);
Duplicate

2025-01-31 22:12 UTC, chosterto commented on firmware/VIPER/release/Core/Src/can.c
> +	MX_CAN_Broadcast_Double_Data(&viper_can, state->CARD_0.TEMPERATURE, SEND_CARD_TEMPERATURE, cardx);
Duplicate

2025-02-01 17:58 UTC, ishanvermani requested changes

2025-02-01 17:58 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +	AT24C04C_WritePages(&at24c04c_1, (uint8_t*) &viper_params, sizeof(VIPER_PARAMS_TypeDef), VIPER_PARAMS_EEPROM_PAGE);
EEPROM has a limited read/write cycle of 100,000 writes. We should NOT be updating the EEPROM every cycle of the main loop. You should include a check to see if there are any differences between viper_state. Enable and viper_params.enable, and ONLY if there's a difference do you update params and write to EEPROM.

2025-02-01 17:58 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +		case VIPER_STATE_INACTIVE: {
Should not have two separate state machines. Consolidate main state machine to one, up here, before you publish card data. It's ok if you increment before you read, and we can start data publishing at card 1 on the first iteration before card 0, that is ok

2025-02-01 17:58 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +			viper_state.CURRENT_CARD++;
for now, lets also increment once per card interval - add this to the increment logic so we only increment at some interval

`(viper_params.CARD_INTERVAL != 0)
				&& (HAL_GetTick() % viper_params.CARD_INTERVAL == 0)`

2025-02-01 17:58 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +	uint8_t pgood[4];
where do we call this!!

2025-02-01 17:58 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +
Rather than having 5 switch statements, you can have one at the end of the function that updates all params of the state together.

2025-02-01 17:58 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +
Improves readiability, and makes it easier to make changes in the future.

2025-02-02 20:23 UTC, ishanvermani commented
Update from Sunday Testing: VIPER is able to read both the input voltage and the input current. The input current is card specific - therefore, every viper_card_state should store the input _current_, not voltage. The input voltage is backplane specific - there's one sensor for the whole thing. So have the Viper Health message carry the input voltage now instead. Update CAN commands to reference that cards are sending input current, not input voltage.

2025-04-22 03:31 UTC, chosterto commented on firmware/VIPER/release/Core/Src/main.c
> +		// AT24C04C_WritePages(&at24c04c_1, (uint8_t*) &viper_params, sizeof(VIPER_PARAMS_TypeDef), VIPER_PARAMS_EEPROM_PAGE);
Uncomment this

2025-06-29 03:54 UTC, ishanvermani commented on firmware/VIPER/release/Core/Src/main.c
> +//	if (c0) {
Keeping Commented - We've had issues with p_good on some cards, where some would incorrectly trigger (or not trigger), shutting down cards when they weren't supposed to be. Keeping this commented to keep activity predictable.

2025-06-29 03:56 UTC, ishanvermani commented
@chosterto give it a peek when you get the chance

2025-06-29 16:42 UTC, chosterto commented
Changes look good, thanks!

2025-06-29 16:42 UTC, merged